site_name: "Red Propulsion Documentation"
site_url: https://docs.redpropulsion.it/
site_author: Red Propulsion
site_description: >-
  Red Docs! Documentazione per HW e SW dei progetti sviluppati da Red Propulsion.
docs_dir: docs


# Repository
repo_name: redpropulsion/AsterCPP/
repo_url: https://github.com/redpropulsion/AsterCPP/

# Copyright
copyright: Copyright © 2025 Red Propulsion


theme:
  name: material
  language: en
  #logo: assets/logo.png
  #favicon: assets/logo.png
  features:
    - content.code.copy
    - content.tabs
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.tabs 
    - toc.follow

plugins:
  - search
  - mkdoxy:
      projects:
        AsterCPP: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: doxy_output/AsterCPP # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories
  - social
  - mermaid2
  - tags:
      listings_map:
        custom-id:
          toc: true

  
nav:
  - Home: index.md
  - API Reference:
    - Overview: api/index.md
  #- Progetti:
      #- AsterCPP Aria:
          #- Overview: api/myProjectCpp/index.md
          #- API Reference: api/myProjectCpp/index.md
      #- AsterCPP Obelics:
          #- Overview: api/myProjectCpp/index.md
          #- API Reference: api/myProjectCpp/index.md
  - Hardware:
    - Overview: hw/index.md
    - Asterics: 
    #TODO: sistemare sta navigazione che non funziona
      - hw/asterics.md
      - PWR: hw/asterics/pwr.md
      - MCU: hw/asterics/mcu.md
      - SENSR: hw/asterics/sensr.md
      - TELEM: hw/asterics/telem.md
    - Obelics: 
      - hw/obelics.md
      - Funzioni disponibili: hw/obelics/funzioni_disponibili.md
  - Runner:
    - Overview: runner/index.md
    - DocsRunner: runner/config_runner.md
  - Guida: 
    - guida/index.md
    - Linee guida: guida/docs-guidelines.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.admonition:
      types:
        - new
        - settings
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - markdown.extensions.md_in_html
  - pymdownx.highlight
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.snippets:
  - pymdownx.tabbed:
      alternate_style: true
# riferimento per mkdoxy: https://github.com/JakubAndrysek/MkDoxy/blob/main/mkdocs.yml

extra:
  social:
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/red_propulsion/

extra_javascript:
#  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
