name: Genera Documentazione AsterCPP mkdocs + doxygen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# deve runnare anche quando viene fatta una PR sulla repo AsterCPP

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdoxy
          sudo apt-get install doxygen graphviz
          
      #- name: Run Doxygen
      #  run: doxygen Doxyfile

      - name: Generate Markdown from doxygen documentation with mkdoxy
        run: |
            mkdir -p docs/api
            mkdoxy \
            --doxygen-output docs/doxygen/xml \
            --output docs/api \
            --project-name "Documentazione Progetto C" \
            --create-toc
      - name: Deploy all documentation with mkdocs
        run: mkdocs gh-deploy --force