name: Genera Documentazione AsterCPP mkdocs + doxygen
permissions:
  contents: write
  pages: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# deve runnare anche quando viene fatta una PR sulla repo AsterCPP

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdoxy mkdocs-material[imaging]
          pip install mkdocs-mermaid2-plugin markdown-callouts
          pip install pymdown-extensions

      - name: Cache system packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Markdown from doxygen documentation with mkdoxy
        continue-on-error: true
        run: |
            mkdir -p docs/api
            mkdoxy \
            --doxygen-output docs/doxygen/xml \
            --output docs/api \
            --project-name "Documentazione Progetto C" \
            --create-toc
      
      - name: Deploy all documentation with mkdocs
        run: mkdocs gh-deploy --force