name: Genera Documentazione AsterCPP mkdocs + doxygen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# deve runnare anche quando viene fatta una PR sulla repo AsterCPP

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdoxy mkdocs-material[imaging]
          sudo apt-get install doxygen graphviz
          echo "${{ runner.tool_cache }}/Python/$(python --version | cut -d' ' -f2)*/bin" >> $GITHUB_PATH

      
      #- name: Add Python to PATH
      #  run: echo "${{ runner.tool_cache }}/Python/3.10*/bin" >> $GITHUB_PATH
      #- name: Run Doxygen
      #  run: doxygen Doxyfile

      - name: Generate Markdown from doxygen documentation with mkdoxy
        continue-on-error: true
        run: |
            mkdir -p docs/api
            mkdoxy \
            --doxygen-output docs/doxygen/xml \
            --output docs/api \
            --project-name "Documentazione Progetto C" \
            --create-toc
      
      - name: Deploy all documentation with mkdocs
        run: mkdocs gh-deploy --force