name: Genera Documentazione AsterCPP mkdocs + doxygen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# deve runnare anche quando viene fatta una PR sulla repo AsterCPP

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Run Doxygen
    #  run: doxygen Doxyfile

    - name: Generate Markdown from doxygen documentation with mkdoxy
      run: |
        mkdir -p docs/api
          ${{ secrets.VENV_DIR }}/bin/mkdoxy \
          --doxygen-output docs/doxygen/xml \
          --output docs/api \
          --project-name "Documentazione Progetto C" \
          --create-toc
    
    - name: Deploy all documentation with mkdocs
      run: ${{ secrets.VENV_DIR }}/bin/mkdocs-material gh-deploy --force
    